version: 0.2

phases:
  build:
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR/tf/src/"
      - cd $CODEBUILD_SRC_DIR/tf/src/
      - echo "Installing dependencies into src file"
      - python3 -m unittest shares.py
artifacts:
  files:
    - 'shares.py'
  discard-paths: yes
